# Generated by Django 4.1 on 2023-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
