# Generated by Django 4.1 on 2023-05-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0002_alter_film_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Actor",
        ),
    ]
