# Generated by Django 4.1 on 2023-05-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0003_delete_actor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.AlterField(
            model_name="film",
            name="image",
            field=models.TextField(blank=True),
        ),
    ]
